name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/studynote

            git fetch origin
            git reset --hard origin/main

            chmod +x gradlew
            ./gradlew build -x test

            sudo systemctl restart studynote

            sudo systemctl status studynote --no-pager